### ISSUE TITLE
Does Status List need to be signed as JWT?

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#41]
@bc-pi questions whether Status List needs to be signed as a JWT and what are the arguments for doing so

**Comment by bc-pi** [comment]
My thinking behind the question was wondering if simplification might be possible/reasonable because the prototypical case (as I understand it anyway) it that an HTTPS URL of the status list is in the signed credential and the verifier obtains the list from that location and checks the status. A signature over the list itself isn't needed in that kind of case.

**Comment by paulbastian** [comment]
See #57
