### ISSUE TITLE
Rename draft to "OAuth Token Status List"?

### ISSUE THREAD

**Issue by aaronpk** [vcstuff/draft-ietf-oauth-status-list#77]
I noticed the draft was renamed from the name it previously had at the last IETF meeting where it was adopted. The previous name was "JWT and CWT Status List" and the new name is "OAuth Status List".

I understand not wanting to have "JWT" and "CWT" in the name, but the new name is somewhat confusing, since it makes it sound like there is a status of OAuth itself somehow.

I suggest renaming this to "OAuth Token Status List" to avoid confusion.

**Comment by paulbastian** [comment]
See #74 
We got feedback from multiple people and hence decided to go for `OAuth Status List` as this seemed a reasonable choice by many. I would not change the title now again before the cutoff, but I'm happy to discuss so in Prague.

**Comment by bc-pi** [comment]
FWIW my comments/feedback on #74 and related conversations were only about the document identifier being `draft-ietf-oauth-status-list`

For the draft title, I'd go with "Token Status List" as suggested https://mailarchive.ietf.org/arch/msg/oauth/ZS3CzShqWUKOHLekweB6mtqbcTI/ 

Note that the document identifier needs to start with draft-ietf-oauth- because of IETF convention and the draft being an OAuth WG item. But the document title doesn't have to have "OAuth" in it.

**Comment by aaronpk** [comment]
After reviewing the discussion I also would support "Token Status List"

**Comment by paulbastian** [comment]
The name of the issue is "Feedback from call of adoption: **Draft title**". How should it not be about the title then?

**Comment by aaronpk** [comment]
I was commenting on the fact that literally all of the comments only mentioned the draft URL.

**Comment by Sakurann** [comment]
I already stated in the ML, but I support `Token Status List"

**Comment by paulbastian** [comment]
"Token Status List" seems the most supported option, if there is no objection, we would rename next week.
